# Предсказывание стоимости акций

**Задача**: Обучить несколько моделей и выбрать лучшую, которая будет предсказывать стоимость акции открытия на следующий день.

Данная работа ещё в процессе. Ожидается добавление всех этапов, их более подробное описание, перевод на английский язык, а также новые попытки улучшения метрики.

## Загрузка данных

In [1]:
# Загрузка необходимых библиотек
import warnings
import re
import os

import pandas as pd
import numpy as np
import yfinance as yf

import seaborn as sns
import matplotlib.pyplot as plt

import optuna
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import make_scorer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [2]:
# настройки
warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)
optuna.logging.disable_default_handler()

# константы
NAME="apple"
TARGET = "Open"
DATA = "2019-01-01"
RANDOM_STATE = 42
TEST_SIZE = 0.3
N_TRAILS = 50

# используемые акции и их тикеты
name_of_stocks = {"apple": "AAPL",
                 "microsoft": "MSFT",
                 "nvidia": "NVDA",
                 "google": "GOOG"}

### Functions

In [3]:
# функция для просмотра данных        
def data_review(data):
    print('ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:')
    display(data.head())
    print(f'\nОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:\n')
    data.info()
    print(f'\n\nКОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:\n\n{data.isna().sum()}\n')
    print(f'\nКОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - {data.duplicated().sum()}\n')
    print('\nСТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:')
    display(data.describe())

In [4]:
def download_and_merge_stocks(stock_dict, start_date):
    """Function for downloding data and merging all list of stocks"""
    # Создаем пустой список для хранения отдельных DataFrame
    merged_data = []

    for name, ticker in stock_dict.items():
        # Загружаем данные
        stock_data = yf.download(ticker, start=start_date, progress=False)
        
        # Переименовываем столбцы
        stock_data = stock_data.add_suffix(f"_{name}")
        stock_data = stock_data.rename(columns={f'Adj Close_{name}': f'Adj_Close_{name}'})
        
        # Добавляем полученные данные в список
        merged_data.append(stock_data)
    
    # Объединяем все данные по индексу (дата)
    merged_df = pd.concat(merged_data, axis=1)
    
    return merged_df

### Загрузка и первичное знакомство с данными

In [5]:
data = download_and_merge_stocks(name_of_stocks, DATA)

# Просмотр первых строк объединенного DataFrame
data_review(data)

ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Low_nvidia,Close_nvidia,Adj_Close_nvidia,Volume_nvidia,Open_google,High_google,Low_google,Close_google,Adj_Close_google,Volume_google
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,38.722500,39.712502,38.557499,39.480000,37.708599,148158800,99.550003,101.750000,98.940002,101.120003,...,3.25125,3.40550,3.378090,508752000,50.828499,52.616001,50.785500,52.292500,52.105282,30652000
2019-01-03,35.994999,36.430000,35.500000,35.547501,33.952530,365248800,100.099998,100.190002,97.199997,97.400002,...,3.19225,3.19975,3.173996,705552000,52.049999,52.848999,50.703499,50.803001,50.621113,36822000
2019-01-04,36.132500,37.137501,35.950001,37.064999,35.401951,234428400,99.720001,102.510002,98.930000,101.930000,...,3.24250,3.40475,3.377345,585620000,51.629501,53.542000,51.370899,53.535500,53.343830,41878000
2019-01-07,37.174999,37.207500,36.474998,36.982498,35.323162,219111200,101.639999,103.269997,100.980003,102.059998,...,3.41075,3.58500,3.556145,709160000,53.575001,53.700001,52.737999,53.419498,53.228245,39638000
2019-01-08,37.389999,37.955002,37.130001,37.687500,35.996529,164101200,103.040001,103.970001,101.709999,102.800003,...,3.42250,3.49575,3.467613,786016000,53.805500,54.228001,53.026501,53.813999,53.621330,35298000

ОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1508 entries, 2019-01-02 to 2024-12-27
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Open_apple           1508 non-null   float64
 1   High_apple           1508 non-null   float64
 2   Low_apple            1508 non-null   float64
 3   Close_apple          1508 non-null   float64
 4   Adj_Close_apple      1508 non-null   float64
 5   Volume_apple         1508 non-null   int64
 6   Open_microsoft       1508 non-null   float64
 7   High_microsoft       1508 non-null   float64
 8   Low_microsoft        1508 non-null   float64
 9   Close_microsoft      1508 non-null   float64
 10  Adj_Close_microsoft  1508 non-null   float64
 11  Volume_microsoft     1508 non-null   int64
 12  Open_nvidia          1508 non-null   float64
 13  High_nvidia          1508 non-null   float64
 14  Low_nvidia           1508 non-null   float64
 15  Close_nvidia         1508 non-null   float64
 16  Adj_Close_nvidia     1508 non-null   float64
 17  Volume_nvidia        1508 non-null   int64
 18  Open_google          1508 non-null   float64
 19  High_google          1508 non-null   float64
 20  Low_google           1508 non-null   float64
 21  Close_google         1508 non-null   float64
 22  Adj_Close_google     1508 non-null   float64
 23  Volume_google        1508 non-null   int64
dtypes: float64(20), int64(4)
memory usage: 294.5 KB


КОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:

Open_apple             0
High_apple             0
Low_apple              0
Close_apple            0
Adj_Close_apple        0
Volume_apple           0
Open_microsoft         0
High_microsoft         0
Low_microsoft          0
Close_microsoft        0
Adj_Close_microsoft    0
Volume_microsoft       0
Open_nvidia            0
High_nvidia            0
Low_nvidia             0
Close_nvidia           0
Adj_Close_nvidia       0
Volume_nvidia          0
Open_google            0
High_google            0
Low_google             0
Close_google           0
Adj_Close_google       0
Volume_google          0
dtype: int64


КОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - 0


СТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Low_nvidia,Close_nvidia,Adj_Close_nvidia,Volume_nvidia,Open_google,High_google,Low_google,Close_google,Adj_Close_google,Volume_google
count,1508.000000,1508.000000,1508.000000,1508.000000,1508.000000,1.508000e+03,1508.000000,1508.000000,1508.000000,1508.000000,...,1508.000000,1508.000000,1508.000000,1.508000e+03,1508.000000,1508.000000,1508.000000,1508.000000,1508.000000,1.508000e+03
mean,136.778934,138.284705,135.403097,136.927304,135.140155,9.424521e+07,266.694609,269.279722,263.999264,266.768740,...,31.988244,32.642674,32.617072,4.487870e+08,109.616241,110.855191,108.509455,109.701712,109.340963,2.757453e+07
std,53.645203,54.091110,53.233233,53.700540,54.113066,5.232798e+07,95.485253,96.093579,94.737599,95.446929,...,36.244126,36.972641,36.977201,1.964614e+08,37.508939,37.853158,37.160194,37.488192,37.409937,1.267446e+07
min,35.994999,36.430000,35.500000,35.547501,33.952530,2.323470e+07,99.550003,100.190002,97.199997,97.400002,...,3.192250,3.199750,3.173996,9.788400e+07,50.828499,52.374500,50.676800,50.803001,50.621113,6.809800e+06
25%,91.213125,92.512501,90.425623,91.207499,88.873869,5.918350e+07,200.000004,203.549995,197.272495,201.122501,...,9.411625,9.529187,9.499413,3.097339e+08,73.505875,74.392374,72.947187,73.712002,73.448095,1.926650e+07
50%,145.510002,147.229996,144.105003,145.860001,143.581306,8.155695e+07,258.904999,261.490005,255.919998,259.144989,...,17.000000,17.586625,17.554289,4.187595e+08,110.077000,111.993752,108.450001,110.515003,110.119335,2.475200e+07
75%,173.857506,175.542496,172.180000,174.235004,172.416500,1.124405e+08,331.864990,334.862503,328.164993,330.889992,...,40.696500,41.652250,41.636782,5.453080e+08,138.350506,139.640003,136.992374,138.440247,137.944614,3.194950e+07
max,258.190002,260.100006,257.630005,259.019989,259.019989,4.265100e+08,467.000000,468.350006,464.459991,467.559998,...,146.259995,148.880005,148.869751,2.511528e+09,198.529999,202.880005,196.690002,198.160004,198.160004,1.241400e+08

Краткие пояснения, что за собой скрывают названия столбцов:

1. **Date**: Дата торгового дня.

2. **Open**: Цена открытия акций в начале торгового дня.

3. **High**: Самая высокая цена, достигнутая акциями в течение торгового дня.

4. **Low**: Самая низкая цена, достигнутая акциями в течение торгового дня.

5. **Close**: Цена закрытия акций в конце торгового дня (без учета корпоративных действий).

6. **Adj Close**: Скорректированная цена закрытия, которая учитывает все корпоративные действия, такие как выплата дивидендов, разделение акций и т. д.

7. **Volume**: Объем торгов, показывающий количество акций, которые были куплены и проданы в течение торгового дня.

## Анализ данных

### Functions

In [6]:
def new_features(df, name=NAME, sma_periods=[3, 5, 10], target=TARGET, max_lag=13):
    """
    Function is adding new features like:
    - differences between all basik columns, 
    - calculated SMA (Simple Moving Average), EMA (Exponential Moving Average) and Volatility (sma_periods)
    - Volume and Price change
    - Features of trend and seasonality
    - Lag features (max_lag)
    - Create Target (target), which is .shift(-1) of target_col
    """
    # Приведение всех столбцов к общему виду
    target_col = f'{target}_{name}'
    
    # Скользящие средние (SMA и EMA) и Волатильность
    for period in sma_periods:
        df[f'SMA_{period}_{name}'] = df[target_col].rolling(window=period).mean()
        df[f'EMA_{period}_{name}'] = df[target_col].ewm(span=period, adjust=False).mean()
        df[f'Volatility_{period}_{name}'] = df[target_col].rolling(window=period).std()
    
    # Процентные изменения
    df[f'Volume_Change_{name}'] = df[f'Volume_{name}'].pct_change()
    df[f'Price_Change_{name}'] = df[target_col].pct_change()
    
        # Создание базовых признаков (на базе разности)
    df[f'Open_High_{name}'] = df[f'Open_{name}'] - df[f'High_{name}']
    df[f'Open_Low_{name}'] = df[f'Open_{name}'] - df[f'Low_{name}']
    df[f'High_Low_{name}'] = df[f'High_{name}'] - df[f'Low_{name}']
    df[f'High_Close_{name}'] = df[f'High_{name}'] - df[f'Close_{name}']
    df[f'Low_Close_{name}'] = df[f'Low_{name}'] - df[f'Close_{name}']
    df[f'Close_Open_{name}'] = df[f'Close_{name}'] - df[f'Open_{name}']
    df[f'AdjClose_Open_{name}'] = df[f'Adj_Close_{name}'] - df[f'Open_{name}']
    df[f'AdjClose_Low_{name}'] = df[f'Adj_Close_{name}'] - df[f'Low_{name}']
    df[f'AdjClose_High_{name}'] = df[f'Adj_Close_{name}'] - df[f'High_{name}']
    df[f'AdjClose_Close_{name}'] = df[f'Adj_Close_{name}'] - df[f'Close_{name}']
    
    # Добавление признаков тренда и сезонности
    df[f'Day_of_Week_{name}'] = df.index.dayofweek
    df[f'Number_of_Week_{name}'] = df.index.isocalendar().week
    df[f'Month_{name}'] = df.index.month
    df[f'Quarter_{name}'] = df.index.quarter
    
    # Добавление лаг-функций
    for lag in range(1, max_lag):
        df[f'Lag_{lag}_{name}'] = df[target_col].shift(lag)
    
    # Добавляем столбец с ценой таргета на следующий день
    df['Target'] = df[target_col].shift(-1)
    df['Low_future'] = df[f'Low_{name}'].shift(-1)
    
    # Удаление строк с NaN значениями, которые появились из-за использования скользящих средних и других вычислений
    df.dropna(inplace=True)
    
    return df

### Features engineering

In [7]:
data = new_features(data)

На этом этапе реализуем генерацию дополнительных признаков для обогащения данных с целью предсказания **цены открытия акций компании Apple на следующий день**. Ниже представлен подробный разбор добавленных признаков.

---

**1. Базовые признаки: разности между основными показателями**

Анализ внутридневной и междневной динамики цен. Эти признаки помогают модели учитывать волатильность и изменения цен в течение дня. Стоит также отменить, что данные признаки были созданы не только для целевой переменной, но и для других компаний.

**Признаки**:
- `Open_High`: Разница между ценой открытия (`Open`) и максимальной ценой (`High`).
- `Open_Low`: Разница между ценой открытия и минимальной ценой (`Low`).
- `High_Low`: Дневной диапазон цен (разница между `High` и `Low`).
- `High_Close`: Разница между максимальной ценой (`High`) и ценой закрытия (`Close`).
- `Low_Close`: Разница между минимальной ценой (`Low`) и ценой закрытия (`Close`).
- `Close_Open`: Разница между ценой закрытия (`Close`) и ценой открытия (`Open`).
- `AdjClose_Open`: Разница между скорректированной ценой закрытия (`Adj Close`) и ценой открытия (`Open`).
- `AdjClose_Low`: Разница между скорректированной ценой закрытия (`Adj Close`) и минимальной ценой (`Low`).
- `AdjClose_High`: Разница между скорректированной ценой закрытия (`Adj Close`) и максимальной ценой (`High`).
- `AdjClose_Close`: Разница между скорректированной ценой закрытия (`Adj Close`) и ценой закрытия (`Close`).

Базовые признаки формируют основу для анализа поведения акций и включают ключевые различия между основными метриками (`Open`, `High`, `Low`, `Close`, `Adj Close`). Например:
- **`Open_High`** позволяет оценить разницу между ценой открытия и максимальной ценой, что может указывать на восходящий тренд.
- **`AdjClose_Low`** помогает учитывать влияние корпоративных действий на минимальную цену в течение дня.

Эти признаки создают дополнительный контекст, который особенно важен для задач временных рядов, где даже небольшие изменения могут быть значимыми для предсказания.

---

**2. Скользящие средние (SMA, EMA) и волатильность**

Выявление трендов и сглаживание данных для получения более информативных признаков. Скользящие средние показывают краткосрочные тренды, а волатильность — уровень риска.

**Признаки**:
  - **SMA** (Simple Moving Average):
    - Примеры: `SMA_3`, `SMA_5`, `SMA_10` — среднее значение за последние 3, 5 и 10 дней.
  - **EMA** (Exponential Moving Average):
    - Похоже на SMA, но с большим весом для недавних данных.
  - **Волатильность** (Volatility):
    - Стандартное отклонение целевой переменной (`Open`) за последние 3, 5 или 10 дней.

---

**3. Процентные изменения**

Анализ относительных изменений объёма торговли и цены. Эти признаки важны для оценки динамики рынка и активности.

**Признаки**:
  - `Volume_Change`: Процентное изменение объёма торговли за день.
  - `Price_Change`: Процентное изменение цены открытия (`Open`) по сравнению с предыдущим днём.
  
---

**4. Признаки тренда и сезонности**

Учёт временных паттернов. Эти признаки позволяют модели учитывать сезонные тренды и их влияние на рынок.

**Признаки**:
  - `Day_of_Week`: День недели (например, понедельник = 0, пятница = 4).
  - `Number_of_Week`: Номер недели года.
  - `Month`: Номер месяца.
  - `Quarter`: Квартал.

---

**5. Лаг-функции**

Предоставление исторического контекста для предсказания. Лаг-признаки важны для анализа временной зависимости, что критично для временных рядов.

**Признаки**:
  - `Lag_1`, `Lag_2`, ..., `Lag_12`: Значения цены открытия (`Open`) за последние 12 дней.

---

**6. Целевая переменная**

Определить метрику, которую нужно предсказывать.

**Признаки**:
  - `Target`: Цена открытия на следующий день (`shift(-1)`).
  - `Low_future`: Минимальная цена на следующий день (`shift(-1)`).

---

**7. Удаление строк с пропусками**

Строки с `NaN`, возникающие из-за вычисления скользящих средних, лагов и других признаков, удаляются для обеспечения корректности данных.

In [8]:
data_review(data)

ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Lag_5_apple,Lag_6_apple,Lag_7_apple,Lag_8_apple,Lag_9_apple,Lag_10_apple,Lag_11_apple,Lag_12_apple,Target,Low_future
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-18,39.375000,39.470001,38.994999,39.205002,37.445942,135004000,107.459999,107.900002,105.910004,107.709999,...,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,35.994999,38.722500,39.102501,38.154999
2019-01-22,39.102501,39.182499,38.154999,38.325001,36.605423,121576000,106.750000,107.099998,104.860001,105.680000,...,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,35.994999,38.537498,37.924999
2019-01-23,38.537498,38.785000,37.924999,38.480000,36.753471,92522400,106.120003,107.040001,105.339996,106.709999,...,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,38.527500,37.935001
2019-01-24,38.527500,38.619999,37.935001,38.174999,36.462158,101766000,106.860001,107.000000,105.339996,106.199997,...,38.270000,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,38.869999,38.580002
2019-01-25,38.869999,39.532501,38.580002,39.439999,37.670395,134142000,107.239998,107.879997,106.199997,107.169998,...,38.549999,38.270000,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,38.947498,38.415001

ОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1495 entries, 2019-01-18 to 2024-12-26
Data columns (total 63 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Open_apple            1495 non-null   float64
 1   High_apple            1495 non-null   float64
 2   Low_apple             1495 non-null   float64
 3   Close_apple           1495 non-null   float64
 4   Adj_Close_apple       1495 non-null   float64
 5   Volume_apple          1495 non-null   int64
 6   Open_microsoft        1495 non-null   float64
 7   High_microsoft        1495 non-null   float64
 8   Low_microsoft         1495 non-null   float64
 9   Close_microsoft       1495 non-null   float64
 10  Adj_Close_microsoft   1495 non-null   float64
 11  Volume_microsoft      1495 non-null   int64
 12  Open_nvidia           1495 non-null   float64
 13  High_nvidia           1495 non-null   float64
 14  Low_nvidia            1495 non-null   float64
 15  Close_nvidia          1495 non-null   float64
 16  Adj_Close_nvidia      1495 non-null   float64
 17  Volume_nvidia         1495 non-null   int64
 18  Open_google           1495 non-null   float64
 19  High_google           1495 non-null   float64
 20  Low_google            1495 non-null   float64
 21  Close_google          1495 non-null   float64
 22  Adj_Close_google      1495 non-null   float64
 23  Volume_google         1495 non-null   int64
 24  SMA_3_apple           1495 non-null   float64
 25  EMA_3_apple           1495 non-null   float64
 26  Volatility_3_apple    1495 non-null   float64
 27  SMA_5_apple           1495 non-null   float64
 28  EMA_5_apple           1495 non-null   float64
 29  Volatility_5_apple    1495 non-null   float64
 30  SMA_10_apple          1495 non-null   float64
 31  EMA_10_apple          1495 non-null   float64
 32  Volatility_10_apple   1495 non-null   float64
 33  Volume_Change_apple   1495 non-null   float64
 34  Price_Change_apple    1495 non-null   float64
 35  Open_High_apple       1495 non-null   float64
 36  Open_Low_apple        1495 non-null   float64
 37  High_Low_apple        1495 non-null   float64
 38  High_Close_apple      1495 non-null   float64
 39  Low_Close_apple       1495 non-null   float64
 40  Close_Open_apple      1495 non-null   float64
 41  AdjClose_Open_apple   1495 non-null   float64
 42  AdjClose_Low_apple    1495 non-null   float64
 43  AdjClose_High_apple   1495 non-null   float64
 44  AdjClose_Close_apple  1495 non-null   float64
 45  Day_of_Week_apple     1495 non-null   int32
 46  Number_of_Week_apple  1495 non-null   UInt32
 47  Month_apple           1495 non-null   int32
 48  Quarter_apple         1495 non-null   int32
 49  Lag_1_apple           1495 non-null   float64
 50  Lag_2_apple           1495 non-null   float64
 51  Lag_3_apple           1495 non-null   float64
 52  Lag_4_apple           1495 non-null   float64
 53  Lag_5_apple           1495 non-null   float64
 54  Lag_6_apple           1495 non-null   float64
 55  Lag_7_apple           1495 non-null   float64
 56  Lag_8_apple           1495 non-null   float64
 57  Lag_9_apple           1495 non-null   float64
 58  Lag_10_apple          1495 non-null   float64
 59  Lag_11_apple          1495 non-null   float64
 60  Lag_12_apple          1495 non-null   float64
 61  Target                1495 non-null   float64
 62  Low_future            1495 non-null   float64
dtypes: UInt32(1), float64(55), int32(3), int64(4)
memory usage: 725.6 KB


КОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:

Open_apple         0
High_apple         0
Low_apple          0
Close_apple        0
Adj_Close_apple    0
                  ..
Lag_10_apple       0
Lag_11_apple       0
Lag_12_apple       0
Target             0
Low_future         0
Length: 63, dtype: int64


КОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - 0


СТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Lag_5_apple,Lag_6_apple,Lag_7_apple,Lag_8_apple,Lag_9_apple,Lag_10_apple,Lag_11_apple,Lag_12_apple,Target,Low_future
count,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1.495000e+03,1495.000000,1495.000000,1495.000000,1495.000000,...,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000
mean,137.493726,139.007420,136.111582,137.642612,135.853581,9.366598e+07,267.900923,270.497679,265.195090,267.974709,...,136.775552,136.632385,136.490407,136.349537,136.208637,136.067662,135.925880,135.786637,137.639850,136.254769
std,53.043193,53.484897,52.644176,53.105240,53.524601,5.170275e+07,94.655417,95.258640,93.925902,94.626629,...,52.930100,52.907255,52.887407,52.870692,52.854107,52.839764,52.823703,52.805367,53.073606,52.670963
min,38.527500,38.619999,37.924999,38.174999,36.462158,2.323470e+07,102.870003,104.099998,102.169998,102.779999,...,37.567501,37.567501,37.567501,37.389999,37.174999,36.132500,35.994999,35.994999,38.527500,37.924999
25%,94.277500,95.677502,93.740002,95.191250,92.755688,5.911500e+07,203.320000,204.869995,200.489998,202.779999,...,93.105000,92.231251,91.621250,91.264999,91.176250,91.051250,90.993752,90.581253,94.603748,93.822502
50%,145.809998,147.470001,144.369995,146.089996,143.916580,8.131220e+07,259.630005,261.970001,256.799988,259.890015,...,145.529999,145.490005,145.470001,145.389999,145.350006,145.259995,145.139999,145.029999,145.809998,144.460007
75%,173.989998,175.815002,172.309998,174.410004,172.522026,1.118815e+08,332.069992,335.165009,328.444992,331.264999,...,173.769997,173.684998,173.494995,173.349998,173.325005,173.240005,173.154999,173.139999,174.004997,172.404999
max,258.190002,260.100006,257.630005,259.019989,259.019989,4.265100e+08,467.000000,468.350006,464.459991,467.559998,...,252.160004,250.080002,247.990005,247.960007,247.960007,247.960007,246.889999,243.990005,258.190002,257.630005

Создание новых признаков позволяет учитывать как краткосрочные тренды и волатильность, так и сезонные закономерности, обеспечивая более полное представление о динамике цен и их взаимосвязях. Это может сделать модель более информативной и эффективной для предсказания цены открытия акций.

## Обучение
### Functions

In [9]:
def optimize_df(df):
    """Уменьшение размерности датафрейма"""
    initial_memory = df.memory_usage(deep=True).sum()
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type == 'float64' or col_type == 'float32':
            # Проверяем, можно ли привести float к int
            if df[col].apply(float.is_integer).all():
                df[col] = pd.to_numeric(df[col], downcast='integer')
            else:
                df[col] = pd.to_numeric(df[col], downcast='float')
        
        elif col_type == 'int64' or col_type == 'int32':
            df[col] = pd.to_numeric(df[col], downcast='integer')
        
        elif col_type == 'object':
            num_unique_values = len(df[col].unique())
            num_total_values = len(df[col])
            if num_unique_values / num_total_values < 0.5:
                df[col] = df[col].astype('category')
        
        elif col_type == 'bool':
            df[col] = df[col].astype('int8')
    
    final_memory = df.memory_usage(deep=True).sum()
    memory_reduction = (initial_memory - final_memory) / initial_memory * 100
    
    print(f"Память до оптимизации: {initial_memory} байт")
    print(f"Память после оптимизации: {final_memory} байт")
    print(f"Сокращение памяти: {memory_reduction:.2f}%")
    
    return df

In [10]:
def plot_feature_importances(model, feature_names, model_name):
    """
    Функция для вывода важности признаков для модели.

    Parameters:
    model (sklearn model): Обученная модель.
    feature_names (list): Список названий признаков.
    model_name (str): Название модели.
    """
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_
    elif hasattr(model, 'coef_'):
        importances = model.coef_
    else:
        raise ValueError(f"Model {model_name} does not have feature importances or coefficients.")

    # Создание DataFrame для удобного отображения
    feature_importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importances
    })
    feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
    
    # Построение графика
    plt.figure(figsize=(10, 6))
    sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
    plt.title(f'Feature Importances for best model - {model_name}')
    plt.show()

### Подготовка к обучению

### Train

## Выбор лучшей модели

## Выводы