# Предсказывание стоимости акций

**Задача**: Обучить несколько моделей и выбрать лучшую, которая будет предсказывать стоимость акции открытия на следующий день.

Данная работа ещё в процессе. Ожидается добавление всех этапов, их более подробное описание, перевод на английский язык, а также новые попытки улучшения метрики.

## Загрузка данных

In [1]:
# Загрузка необходимых библиотек
import warnings
import re
import os

import pandas as pd
import numpy as np
import yfinance as yf

import seaborn as sns
import matplotlib.pyplot as plt

import optuna
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import make_scorer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [2]:
# настройки
warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)
optuna.logging.disable_default_handler()

# константы
NAME="apple"
TARGET = "Open"
DATA = "2019-01-01"
RANDOM_STATE = 42
TEST_SIZE = 0.3
N_TRAILS = 50

# используемые акции и их тикеты
name_of_stocks = {"apple": "AAPL",
                 "microsoft": "MSFT",
                 "nvidia": "NVDA",
                 "google": "GOOG"}

### Functions

In [3]:
# функция для просмотра данных        
def data_review(data):
    print('ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:')
    display(data.head())
    print(f'\nОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:\n')
    data.info()
    print(f'\n\nКОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:\n\n{data.isna().sum()}\n')
    print(f'\nКОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - {data.duplicated().sum()}\n')
    print('\nСТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:')
    display(data.describe())

In [4]:
def download_and_merge_stocks(stock_dict, start_date):
    """Function for downloding data and merging all list of stocks"""
    # Создаем пустой список для хранения отдельных DataFrame
    merged_data = []

    for name, ticker in stock_dict.items():
        # Загружаем данные
        stock_data = yf.download(ticker, start=start_date, progress=False)
        
        # Переименовываем столбцы
        stock_data = stock_data.add_suffix(f"_{name}")
        stock_data = stock_data.rename(columns={f'Adj Close_{name}': f'Adj_Close_{name}'})
        
        # Добавляем полученные данные в список
        merged_data.append(stock_data)
    
    # Объединяем все данные по индексу (дата)
    merged_df = pd.concat(merged_data, axis=1)
    
    return merged_df

### Загрузка и первичное знакомство с данными

In [5]:
data = download_and_merge_stocks(name_of_stocks, DATA)

# Просмотр первых строк объединенного DataFrame
data_review(data)

ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Low_nvidia,Close_nvidia,Adj_Close_nvidia,Volume_nvidia,Open_google,High_google,Low_google,Close_google,Adj_Close_google,Volume_google
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-02,38.722500,39.712502,38.557499,39.480000,37.708599,148158800,99.550003,101.750000,98.940002,101.120003,...,3.25125,3.40550,3.378090,508752000,50.828499,52.616001,50.785500,52.292500,52.105282,30652000
2019-01-03,35.994999,36.430000,35.500000,35.547501,33.952538,365248800,100.099998,100.190002,97.199997,97.400002,...,3.19225,3.19975,3.173996,705552000,52.049999,52.848999,50.703499,50.803001,50.621113,36822000
2019-01-04,36.132500,37.137501,35.950001,37.064999,35.401947,234428400,99.720001,102.510002,98.930000,101.930000,...,3.24250,3.40475,3.377346,585620000,51.629501,53.542000,51.370899,53.535500,53.343830,41878000
2019-01-07,37.174999,37.207500,36.474998,36.982498,35.323151,219111200,101.639999,103.269997,100.980003,102.059998,...,3.41075,3.58500,3.556146,709160000,53.575001,53.700001,52.737999,53.419498,53.228245,39638000
2019-01-08,37.389999,37.955002,37.130001,37.687500,35.996521,164101200,103.040001,103.970001,101.709999,102.800003,...,3.42250,3.49575,3.467614,786016000,53.805500,54.228001,53.026501,53.813999,53.621330,35298000

ОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1506 entries, 2019-01-02 to 2024-12-24
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Open_apple           1506 non-null   float64
 1   High_apple           1506 non-null   float64
 2   Low_apple            1506 non-null   float64
 3   Close_apple          1506 non-null   float64
 4   Adj_Close_apple      1506 non-null   float64
 5   Volume_apple         1506 non-null   int64
 6   Open_microsoft       1506 non-null   float64
 7   High_microsoft       1506 non-null   float64
 8   Low_microsoft        1506 non-null   float64
 9   Close_microsoft      1506 non-null   float64
 10  Adj_Close_microsoft  1506 non-null   float64
 11  Volume_microsoft     1506 non-null   int64
 12  Open_nvidia          1506 non-null   float64
 13  High_nvidia          1506 non-null   float64
 14  Low_nvidia           1506 non-null   float64
 15  Close_nvidia         1506 non-null   float64
 16  Adj_Close_nvidia     1506 non-null   float64
 17  Volume_nvidia        1506 non-null   int64
 18  Open_google          1506 non-null   float64
 19  High_google          1506 non-null   float64
 20  Low_google           1506 non-null   float64
 21  Close_google         1506 non-null   float64
 22  Adj_Close_google     1506 non-null   float64
 23  Volume_google        1506 non-null   int64
dtypes: float64(20), int64(4)
memory usage: 294.1 KB


КОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:

Open_apple             0
High_apple             0
Low_apple              0
Close_apple            0
Adj_Close_apple        0
Volume_apple           0
Open_microsoft         0
High_microsoft         0
Low_microsoft          0
Close_microsoft        0
Adj_Close_microsoft    0
Volume_microsoft       0
Open_nvidia            0
High_nvidia            0
Low_nvidia             0
Close_nvidia           0
Adj_Close_nvidia       0
Volume_nvidia          0
Open_google            0
High_google            0
Low_google             0
Close_google           0
Adj_Close_google       0
Volume_google          0
dtype: int64


КОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - 0


СТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Low_nvidia,Close_nvidia,Adj_Close_nvidia,Volume_nvidia,Open_google,High_google,Low_google,Close_google,Adj_Close_google,Volume_google
count,1506.000000,1506.000000,1506.000000,1506.000000,1506.000000,1.506000e+03,1506.000000,1506.000000,1506.000000,1506.000000,...,1506.000000,1506.000000,1506.000000,1.506000e+03,1506.000000,1506.000000,1506.000000,1506.000000,1506.000000,1.506000e+03
mean,136.617937,138.123861,135.243825,136.767440,134.977918,9.432265e+07,266.468698,269.055438,263.776832,266.546228,...,31.849822,32.502133,32.476497,4.491903e+08,109.500854,110.740145,108.396028,109.587677,109.226449,2.759586e+07
std,53.498367,53.946420,53.088568,53.556455,53.965286,5.231918e+07,95.346927,95.959795,94.603252,95.314465,...,36.068304,36.795206,36.799697,1.962774e+08,37.399794,37.746242,37.054053,37.382048,37.302359,1.266884e+07
min,35.994999,36.430000,35.500000,35.547501,33.952538,2.096501e+07,99.550003,100.190002,97.199997,97.400002,...,3.192250,3.199750,3.173996,9.788400e+07,50.828499,52.374500,50.676800,50.803001,50.621113,6.401746e+06
25%,91.139376,92.302502,90.141874,91.202497,88.868982,5.923115e+07,199.900005,203.349998,196.797497,200.767498,...,9.408875,9.527562,9.497794,3.103232e+08,73.478622,74.356123,72.942560,73.690998,73.427166,1.928492e+07
50%,145.480003,147.209999,144.050003,145.855003,143.556671,8.166885e+07,258.854996,261.404999,255.820000,258.844986,...,16.972500,17.556625,17.531030,4.191295e+08,109.919250,111.973751,108.305000,110.435253,110.039867,2.477700e+07
75%,173.797501,175.457504,172.142494,174.187496,172.374058,1.124727e+08,331.702499,334.637512,327.767494,330.687500,...,40.587998,41.330501,41.315152,5.456020e+08,138.274754,139.592381,136.867252,138.401878,137.906361,3.196450e+07
max,255.490005,258.209991,255.309998,258.200012,258.200012,4.265100e+08,467.000000,468.350006,464.459991,467.559998,...,146.259995,148.880005,148.869751,2.511528e+09,198.529999,202.880005,196.690002,198.160004,198.160004,1.241400e+08

Краткие пояснения, что за собой скрывают названия столбцов:

1. **Date**: Дата торгового дня.

2. **Open**: Цена открытия акций в начале торгового дня.

3. **High**: Самая высокая цена, достигнутая акциями в течение торгового дня.

4. **Low**: Самая низкая цена, достигнутая акциями в течение торгового дня.

5. **Close**: Цена закрытия акций в конце торгового дня (без учета корпоративных действий).

6. **Adj Close**: Скорректированная цена закрытия, которая учитывает все корпоративные действия, такие как выплата дивидендов, разделение акций и т. д.

7. **Volume**: Объем торгов, показывающий количество акций, которые были куплены и проданы в течение торгового дня.

## Анализ данных

### Functions

In [6]:
def new_features(df, name=NAME, sma_periods=[3, 5, 10], target=TARGET, max_lag=13):
    """
    Function is adding new features like:
    - differences between all basik columns, 
    - calculated SMA (Simple Moving Average), EMA (Exponential Moving Average) and Volatility (sma_periods)
    - Volume and Price change
    - Features of trend and seasonality
    - Lag features (max_lag)
    - Create Target (target), which is .shift(-1) of target_col
    """
    # Приведение всех столбцов к общему виду
    target_col = f'{target}_{name}'
    
    # Создание базовых признаков (на базе разности)
    df[f'Open_High_{name}'] = df[f'Open_{name}'] - df[f'High_{name}']
    df[f'Open_Low_{name}'] = df[f'Open_{name}'] - df[f'Low_{name}']
    df[f'High_Low_{name}'] = df[f'High_{name}'] - df[f'Low_{name}']
    df[f'High_Close_{name}'] = df[f'High_{name}'] - df[f'Close_{name}']
    df[f'Low_Close_{name}'] = df[f'Low_{name}'] - df[f'Close_{name}']
    df[f'Close_Open_{name}'] = df[f'Close_{name}'] - df[f'Open_{name}']
    df[f'AdjClose_Open_{name}'] = df[f'Adj_Close_{name}'] - df[f'Open_{name}']
    df[f'AdjClose_Low_{name}'] = df[f'Adj_Close_{name}'] - df[f'Low_{name}']
    df[f'AdjClose_High_{name}'] = df[f'Adj_Close_{name}'] - df[f'High_{name}']
    df[f'AdjClose_Close_{name}'] = df[f'Adj_Close_{name}'] - df[f'Close_{name}']
    
    # Скользящие средние (SMA и EMA) и Волатильность
    for period in sma_periods:
        df[f'SMA_{period}_{name}'] = df[target_col].rolling(window=period).mean()
        df[f'EMA_{period}_{name}'] = df[target_col].ewm(span=period, adjust=False).mean()
        df[f'Volatility_{period}_{name}'] = df[target_col].rolling(window=period).std()
    
    # Процентные изменения
    df[f'Volume_Change_{name}'] = df[f'Volume_{name}'].pct_change()
    df[f'Price_Change_{name}'] = df[target_col].pct_change()
    
    # Добавление признаков тренда и сезонности
    df[f'Day_of_Week_{name}'] = df.index.dayofweek
    df[f'Number_of_Week_{name}'] = df.index.isocalendar().week
    df[f'Month_{name}'] = df.index.month
    df[f'Quarter_{name}'] = df.index.quarter
    
    # Добавление лаг-функций
    for lag in range(1, max_lag):
        df[f'Lag_{lag}_{name}'] = df[target_col].shift(lag)
    
    # Добавляем столбец с ценой максимума на следующий день
    df['Target'] = df[target_col].shift(-1)
    df['Low_future'] = df[f'Low_{name}'].shift(-1)
    
    # Удаление строк с NaN значениями, которые появились из-за использования скользящих средних и других вычислений
    df.dropna(inplace=True)
    
    return df

### Анализ данных

In [7]:
data = new_features(data)

In [8]:
data_review(data)

ПЕРВЫЕ 5 СТРОЧЕК С ДАННЫМИ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Lag_5_apple,Lag_6_apple,Lag_7_apple,Lag_8_apple,Lag_9_apple,Lag_10_apple,Lag_11_apple,Lag_12_apple,Target,Low_future
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-18,39.375000,39.470001,38.994999,39.205002,37.445942,135004000,107.459999,107.900002,105.910004,107.709999,...,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,35.994999,38.722500,39.102501,38.154999
2019-01-22,39.102501,39.182499,38.154999,38.325001,36.605423,121576000,106.750000,107.099998,104.860001,105.680000,...,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,35.994999,38.537498,37.924999
2019-01-23,38.537498,38.785000,37.924999,38.480000,36.753460,92522400,106.120003,107.040001,105.339996,106.709999,...,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,36.132500,38.527500,37.935001
2019-01-24,38.527500,38.619999,37.935001,38.174999,36.462147,101766000,106.860001,107.000000,105.339996,106.199997,...,38.270000,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,37.174999,38.869999,38.580002
2019-01-25,38.869999,39.532501,38.580002,39.439999,37.670391,134142000,107.239998,107.879997,106.199997,107.169998,...,38.549999,38.270000,37.567501,37.712502,38.220001,38.125000,37.822498,37.389999,38.947498,38.415001

ОБЩАЯ ИНФОРМАЦИЯ О ДАННЫХ:

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1493 entries, 2019-01-18 to 2024-12-23
Data columns (total 63 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Open_apple            1493 non-null   float64
 1   High_apple            1493 non-null   float64
 2   Low_apple             1493 non-null   float64
 3   Close_apple           1493 non-null   float64
 4   Adj_Close_apple       1493 non-null   float64
 5   Volume_apple          1493 non-null   int64
 6   Open_microsoft        1493 non-null   float64
 7   High_microsoft        1493 non-null   float64
 8   Low_microsoft         1493 non-null   float64
 9   Close_microsoft       1493 non-null   float64
 10  Adj_Close_microsoft   1493 non-null   float64
 11  Volume_microsoft      1493 non-null   int64
 12  Open_nvidia           1493 non-null   float64
 13  High_nvidia           1493 non-null   float64
 14  Low_nvidia            1493 non-null   float64
 15  Close_nvidia          1493 non-null   float64
 16  Adj_Close_nvidia      1493 non-null   float64
 17  Volume_nvidia         1493 non-null   int64
 18  Open_google           1493 non-null   float64
 19  High_google           1493 non-null   float64
 20  Low_google            1493 non-null   float64
 21  Close_google          1493 non-null   float64
 22  Adj_Close_google      1493 non-null   float64
 23  Volume_google         1493 non-null   int64
 24  Open_High_apple       1493 non-null   float64
 25  Open_Low_apple        1493 non-null   float64
 26  High_Low_apple        1493 non-null   float64
 27  High_Close_apple      1493 non-null   float64
 28  Low_Close_apple       1493 non-null   float64
 29  Close_Open_apple      1493 non-null   float64
 30  AdjClose_Open_apple   1493 non-null   float64
 31  AdjClose_Low_apple    1493 non-null   float64
 32  AdjClose_High_apple   1493 non-null   float64
 33  AdjClose_Close_apple  1493 non-null   float64
 34  SMA_3_apple           1493 non-null   float64
 35  EMA_3_apple           1493 non-null   float64
 36  Volatility_3_apple    1493 non-null   float64
 37  SMA_5_apple           1493 non-null   float64
 38  EMA_5_apple           1493 non-null   float64
 39  Volatility_5_apple    1493 non-null   float64
 40  SMA_10_apple          1493 non-null   float64
 41  EMA_10_apple          1493 non-null   float64
 42  Volatility_10_apple   1493 non-null   float64
 43  Volume_Change_apple   1493 non-null   float64
 44  Price_Change_apple    1493 non-null   float64
 45  Day_of_Week_apple     1493 non-null   int32
 46  Number_of_Week_apple  1493 non-null   UInt32
 47  Month_apple           1493 non-null   int32
 48  Quarter_apple         1493 non-null   int32
 49  Lag_1_apple           1493 non-null   float64
 50  Lag_2_apple           1493 non-null   float64
 51  Lag_3_apple           1493 non-null   float64
 52  Lag_4_apple           1493 non-null   float64
 53  Lag_5_apple           1493 non-null   float64
 54  Lag_6_apple           1493 non-null   float64
 55  Lag_7_apple           1493 non-null   float64
 56  Lag_8_apple           1493 non-null   float64
 57  Lag_9_apple           1493 non-null   float64
 58  Lag_10_apple          1493 non-null   float64
 59  Lag_11_apple          1493 non-null   float64
 60  Lag_12_apple          1493 non-null   float64
 61  Target                1493 non-null   float64
 62  Low_future            1493 non-null   float64
dtypes: UInt32(1), float64(55), int32(3), int64(4)
memory usage: 724.6 KB


КОЛИЧЕСТВО ПРОПУСКОВ В ДАННЫХ:

Open_apple         0
High_apple         0
Low_apple          0
Close_apple        0
Adj_Close_apple    0
                  ..
Lag_10_apple       0
Lag_11_apple       0
Lag_12_apple       0
Target             0
Low_future         0
Length: 63, dtype: int64


КОЛИЧЕСТВО ДУБЛИКАТОВ В ДАННЫХ - 0


СТАТИСТИКА ПО ЧИСЛОВЫМ СТОЛБЦАМ:

,Open_apple,High_apple,Low_apple,Close_apple,Adj_Close_apple,Volume_apple,Open_microsoft,High_microsoft,Low_microsoft,Close_microsoft,...,Lag_5_apple,Lag_6_apple,Lag_7_apple,Lag_8_apple,Lag_9_apple,Lag_10_apple,Lag_11_apple,Lag_12_apple,Target,Low_future
count,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1.493000e+03,1493.000000,1493.000000,1493.000000,1493.000000,...,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000,1493.000000
mean,137.333851,138.846472,135.950365,137.480566,135.689139,9.375761e+07,267.674581,270.270255,264.967073,267.745981,...,136.622378,136.481812,136.341157,136.200836,136.059654,135.918490,135.780623,135.643860,137.478604,136.095251
std,52.898305,53.339397,52.494583,52.955689,53.371303,5.167660e+07,94.516301,95.119313,93.781708,94.483166,...,52.799618,52.782285,52.765190,52.749569,52.732326,52.717531,52.709515,52.696261,52.925752,52.525313
min,38.527500,38.619999,37.924999,38.174999,36.462147,2.404830e+07,102.870003,104.099998,102.169998,102.779999,...,37.567501,37.567501,37.567501,37.389999,37.174999,36.132500,35.994999,35.994999,38.527500,37.924999
25%,94.187500,95.375000,93.712502,95.040001,92.608299,5.914450e+07,203.139999,204.699997,200.119995,202.679993,...,92.500000,91.962502,91.279999,91.250000,91.102501,91.000000,90.987503,90.175003,94.367500,93.767502
50%,145.759995,147.460007,144.259995,146.059998,143.903152,8.137870e+07,259.540009,261.779999,256.609985,259.619995,...,145.490005,145.470001,145.389999,145.350006,145.259995,145.139999,145.029999,145.029999,145.809998,144.369995
75%,173.880005,175.729996,172.210007,174.309998,172.447495,1.119123e+08,331.880005,334.899994,328.299988,331.160004,...,173.619995,173.369995,173.330002,173.320007,173.160004,173.149994,173.130005,173.050003,173.979996,172.309998
max,254.770004,255.649994,253.449997,255.270004,255.270004,4.265100e+08,467.000000,468.350006,464.459991,467.559998,...,247.990005,247.960007,247.960007,247.960007,246.889999,243.990005,243.990005,243.990005,255.490005,255.309998

## Обучение
### Functions

In [9]:
def optimize_df(df):
    """Уменьшение размерности датафрейма"""
    initial_memory = df.memory_usage(deep=True).sum()
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type == 'float64' or col_type == 'float32':
            # Проверяем, можно ли привести float к int
            if df[col].apply(float.is_integer).all():
                df[col] = pd.to_numeric(df[col], downcast='integer')
            else:
                df[col] = pd.to_numeric(df[col], downcast='float')
        
        elif col_type == 'int64' or col_type == 'int32':
            df[col] = pd.to_numeric(df[col], downcast='integer')
        
        elif col_type == 'object':
            num_unique_values = len(df[col].unique())
            num_total_values = len(df[col])
            if num_unique_values / num_total_values < 0.5:
                df[col] = df[col].astype('category')
        
        elif col_type == 'bool':
            df[col] = df[col].astype('int8')
    
    final_memory = df.memory_usage(deep=True).sum()
    memory_reduction = (initial_memory - final_memory) / initial_memory * 100
    
    print(f"Память до оптимизации: {initial_memory} байт")
    print(f"Память после оптимизации: {final_memory} байт")
    print(f"Сокращение памяти: {memory_reduction:.2f}%")
    
    return df

In [10]:
def plot_feature_importances(model, feature_names, model_name):
    """
    Функция для вывода важности признаков для модели.

    Parameters:
    model (sklearn model): Обученная модель.
    feature_names (list): Список названий признаков.
    model_name (str): Название модели.
    """
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_
    elif hasattr(model, 'coef_'):
        importances = model.coef_
    else:
        raise ValueError(f"Model {model_name} does not have feature importances or coefficients.")

    # Создание DataFrame для удобного отображения
    feature_importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importances
    })
    feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
    
    # Построение графика
    plt.figure(figsize=(10, 6))
    sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
    plt.title(f'Feature Importances for best model - {model_name}')
    plt.show()

### Подготовка к обучению

### Train

## Выбор лучшей модели

## Выводы